### ISSUE TITLE
updating instructions

### ISSUE THREAD

**Issue by Sinasta** [wassimj/topologicPy#18]
Hello there,. i would just like to ask how the procedure is on linux to update topologicpy and topologic? thank you

**Comment by wassimj** [comment]
Start by deleting topologicPy in the topologicbim folder (the working folder)
Then search for the topologic 'egg' in the site-packages folder in your python installation and delete it.
then upgrade  cppyy to version 1.9.4
`pip install cppyy==1.9.4 --upgrade`
Check that:

1. cppyy is version 1.9.4
2. CPyCppy is version 1.12.3
2.  cppyy-cling is version 6.21.6
3.  cppyy-backend is version 1.14.3

Then re-install TopologicPy and run the build and install scripts (start from Step 5 in readme.md)

There is no need to re-install and rebuild topologic because we have not changed or updated the code

**Comment by Sinasta** [comment]
Thank you!
