### ISSUE TITLE
Topology.Difference(b1, b, tranDict=True)

### ISSUE THREAD

**Issue by gaoxipeng** [wassimj/topologicpy#25]
from topologicpy.Face import Face
from topologicpy.Topology import Topology

f1 = Face.Rectangle()
f2 = Face.Rectangle(width=10, length=10)
r = Topology.Difference(f2, f1, tranDict=True)

Why does tranDict=True cause Topology.ExportToOBJ - Error: the input vertex is not a valid vertex. Returning None?

**Comment by wassimj** [comment]
Dear @gaoxipeng,
Thank you for reporting this bug. This has now been fixed and a new version of topologicpy has been released (v. 0.4.33). if you continue to find any problem, please let me know. Otherwise, kindly close this issue. If I don't hear from you in a few days, I will assume this is fixed and will close the issue myself. Thank you again for your help with topologicpy.
