### ISSUE TITLE
Plotly.FigureByConfusionMatrix() seems to mix up axis

### ISSUE THREAD

**Issue by Sinasta** [wassimj/topologicpy#4]
i might be wrong but i think in those lines:
https://github.com/wassimj/topologicpy/blob/05a1cb52843ee27d8711fc2207336e5e1e988e53/Plotly.py#L658-L659
and those:
https://github.com/wassimj/topologicpy/blob/05a1cb52843ee27d8711fc2207336e5e1e988e53/Plotly.py#L673-L674
i and j should be switched in order to show the values at their correct position.

**Comment by wassimj** [comment]
You might be right, but I don't have time to check it. Can you provide proof here (some example) that indeed they are reversed?

**Comment by wassimj** [comment]
Found a free minute and tested it. You are right. They are reversed. Will be fixed with the next release.

**Comment by wassimj** [comment]
This has now been fixed in the latest release. Also improved colour and text display (labels have a translucent background to improve contrast and clarity). Number of predictions can now be displayed as totals or normalised so you can more easily tell the proportion of correct vs. wrong predictions.
