### ISSUE TITLE
Results of Topology.SelfMerge and Cluster.MergeCells

### ISSUE THREAD

**Issue by martinvrielink** [wassimj/topologicpy#48]
Hi Wassim,
Going form Cells to CellComplexes we could use different approaches. I have used:

- Topology.SelfMerge
- Cluster.MergeCells

I use these and not CellComplex.ByCells because in practice there could be a situation where a cell is situated freely from the CellComplex.

However the Topology.SelfMerge and Cluster.MergeCells doe not give the same result as CellComplex.ByCells. In this situation I know all the cells can form a cellcomplex, thus CellComplex.ByCells can be used.

Am i missing something or is this an issue?

Kind regards, Martin Vrielink
Cells:
![image](https://github.com/wassimj/topologicpy/assets/167056277/c07a5c0e-9612-49b7-967d-0e1ba0141a55)
Graph Topology.SelfMerge and Cluster.MergeCells:
![image](https://github.com/wassimj/topologicpy/assets/167056277/1a8ea32d-190c-4ea5-9903-d04987005507)
Graph CellComplex.ByCells:
![image](https://github.com/wassimj/topologicpy/assets/167056277/6cbf14b9-ccd9-44c5-99d3-f2f87af1b4e3)

Notebook:
[Situation 03 - CellComplex.zip](https://github.com/wassimj/topologicpy/files/14974548/Situation.03.-.CellComplex.zip)
BREPS:
(https://github.com/wassimj/topologicpy/files/14974505/Situation.03.-.Cellcomplex.Dreven1C.zip)

**Comment by wassimj** [comment]
@martinvrielink Since these methods follow a different algorithm internally, they will unfortunately at times produce different result if not all the steps are successful. The Cluster.SelfMerge will start merging cells to make a CellComplex and when no more cells can be added to a CellComplex, a new CellComplex is started to see if any leftover cells can be added to it etc etc. So that is why you are seeing the graph having islands. I will revisit the algorithms when I have a chance to see if they can be made more predictable and robust. Will post here if I make any improvements.
